### ISSUE TITLE
Is there a reason the NewType doesn't create a table with a "new" function defined?

### ISSUE THREAD

**Issue by bbuck** [layeh/gopher-luar#2]
In Lua code that I've seen written before, and some tutorial, it seems that Objects are generally created where the Table has a method called "new" defined on it. Allowing code like:

```lua
d = Dog:new()
```

While the `NewType` function in luar adds a type where you create instances by calling the named function like:

```lua
d = Dog()
```

Was this done for a specific reason, would it be simple to provide the first option as an alternative?

**Comment by bontibon** [comment]
`NewType` is somewhat flexible, as it returns a function and that can be put wherever it is needed. In your example, Go code probably looked something like this:

```go
L.SetGlobal("Dog", luar.NewType(Dog{}))
```

Meaning it would be accessed by doing:

```lua
d = Dog()
```

But, instead of that, you could create a new table called `Dog` and store it a field named `new`:

```go
dog := L.NewTable()
dog.RawSetH(lua.LString("new"), luar.NewType(Dog{}))
L.SetGlobal("Dog", dog)
```

Then it could be accessed with:

```lua
d = Dog.new()
```

However, this isn't that great if `Dog` has a constructor that accepts some arguments (e.g. `func NewDog(name string) &Dog`). An alternative to using `NewType` would be to expose your `NewDog` constructor in the following manner:

```go
dog := L.NewTable()
dog.RawSetH(lua.LString("new"), luar.New(NewDog))
L.SetGlobal("Dog", dog)
```

And accessing that in Lua:

```lua
d = Dog.new("Spot")
```

Does this work for your situation?

**Comment by bbuck** [comment]
That's what I kind of figured the approach would be. I supposed I was much too sleepy last night to really get that working.

Thanks!
