### ISSUE TITLE
use L.NewTable() for slice and array in New

### ISSUE THREAD

**Issue by brentp** [layeh/gopher-luar#7]
currently, New() creates a userdata for slice and array, it would be nice if it instead create a new table.

**Comment by bontibon** [comment]
I'm not fully convinced this is in the scope of the library, but let's assume it is for a second. In order to implement this, it seems like two changes would have to be made:

1. Add an optional flag to `luar.New` to tell it to convert Go slices and arrays to Lua tables. That flag would only affect the value passed to `luar.New`, not any nested slices that might be created by the value (e.g. if you pass a struct to `luar.New` that has a `[]int` field, reading that field would still emit userdata).
2. Add a struct tag option for slice and array fields that indicates it should be converted to a Lua table, not userdata. Ex:

 ```go
type A struct {
       Points []int `luar:",table"`
}
```

Am I missing anything?

**Comment by brentp** [comment]
I dont know about the scope of the library and I didn't realize how large of a change it would be. I thought it would be something like this

```diff
diff --git a/luar.go b/luar.go
index 0b8478b..7375994 100644
--- a/luar.go
+++ b/luar.go
@@ -63,7 +63,14 @@ func New(L *lua.LState, value interface{}) lua.LValue {
                return lua.LNumber(float64(val.Uint()))
        case reflect.Float32, reflect.Float64:
                return lua.LNumber(val.Float())
-       case reflect.Array, reflect.Chan, reflect.Map, reflect.Ptr, reflect.Slice, reflect.Struct:
+       case reflect.Array, reflect.Slice:
+               lt := L.CreateTable(val.Len(), 0)
+               for i := 0; i < val.Len(); i++ {
+                       ival := val.Index(i)
+                       lt.RawSetInt(i+1, New(L, ival.Interface()))
+               }
+               return lt
+       case reflect.Chan, reflect.Map, reflect.Ptr, reflect.Struct:
                ud := L.NewUserData()
                ud.Value = val.Interface()
                ud.Metatable = getMetatable(L, val)
```

**Comment by bontibon** [comment]
That change cannot be done as modifications to the Lua table are not reflected in the backing Go slice or array; reflecting the changes is an important feature of the library.

**Comment by brentp** [comment]
Ah, right. That makes sense. I understand if you think this is outside of the scope of the library.

**Comment by lochv** [comment]
hi, @brentp
did you solved problem?
